language: node_js

node_js:
  - "lts/*"

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    on:
      branch: master
      tags: true

  - provider: npm
    edge:
      branch: master
    registry: npm.pkg.github.com
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    on:
      branch: master
      tags: true
